[package]
name = "dog_food_for_you"
version = "0.1.0"
authors = ["Mark Lodato <mark@thegnar.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
